# Generated by Django 4.2 on 2026-01-10 10:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(max_length=100, unique=True, verbose_name='CoinGecko ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('current_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Текущая цена (USD)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL иконки')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Общее количество')),
                ('avg_buy_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Средняя цена покупки (USD)')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Всего инвестировано (USD)')),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.cryptocurrency', verbose_name='Криптовалюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
                'ordering': ['-total_invested'],
                'unique_together': {('user', 'cryptocurrency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=4, verbose_name='Тип транзакции')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Цена за единицу (USD)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Общая сумма (USD)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
